/* Capitales, par code pays. Le premier nom est celui affiché ; les suivants
   sont aussi acceptés en réponse (autre capitale officielle, siège du
   gouvernement, nom anglais ou local, ancien nom courant). */
var CAPITALS = {
  af: ["Kaboul", "Kabul"],
  za: ["Pretoria", "Le Cap", "Cape Town", "Bloemfontein"],
  al: ["Tirana"],
  dz: ["Alger", "Algiers"],
  de: ["Berlin"],
  ad: ["Andorre-la-Vieille", "Andorra la Vella"],
  ao: ["Luanda"],
  ag: ["Saint John's", "Saint Johns"],
  sa: ["Riyad", "Riyadh"],
  ar: ["Buenos Aires"],
  am: ["Erevan", "Yerevan"],
  au: ["Canberra"],
  at: ["Vienne", "Vienna", "Wien"],
  az: ["Bakou", "Baku"],
  bs: ["Nassau"],
  bh: ["Manama"],
  bd: ["Dacca", "Dhaka"],
  bb: ["Bridgetown"],
  be: ["Bruxelles", "Brussels", "Brussel"],
  bz: ["Belmopan"],
  bj: ["Porto-Novo", "Cotonou"],
  bt: ["Thimphou", "Thimphu"],
  by: ["Minsk"],
  bo: ["Sucre", "La Paz"],
  ba: ["Sarajevo"],
  bw: ["Gaborone"],
  br: ["Brasilia", "Brasília"],
  bn: ["Bandar Seri Begawan"],
  bg: ["Sofia"],
  bf: ["Ouagadougou"],
  bi: ["Gitega", "Bujumbura"],
  kh: ["Phnom Penh"],
  cm: ["Yaoundé", "Yaounde"],
  ca: ["Ottawa"],
  cv: ["Praia"],
  cf: ["Bangui"],
  cl: ["Santiago", "Santiago du Chili"],
  cn: ["Pékin", "Beijing"],
  cy: ["Nicosie", "Nicosia"],
  co: ["Bogota", "Bogotá"],
  km: ["Moroni"],
  cg: ["Brazzaville"],
  cd: ["Kinshasa"],
  kp: ["Pyongyang"],
  kr: ["Séoul", "Seoul"],
  cr: ["San José", "San Jose"],
  ci: ["Yamoussoukro", "Abidjan"],
  hr: ["Zagreb"],
  cu: ["La Havane", "Havana", "La Habana"],
  dk: ["Copenhague", "Copenhagen", "København"],
  dj: ["Djibouti"],
  dm: ["Roseau"],
  do: ["Saint-Domingue", "Santo Domingo"],
  eg: ["Le Caire", "Cairo"],
  ae: ["Abou Dabi", "Abu Dhabi"],
  ec: ["Quito"],
  er: ["Asmara"],
  es: ["Madrid"],
  ee: ["Tallinn"],
  sz: ["Mbabane", "Lobamba"],
  us: ["Washington", "Washington D.C.", "Washington DC"],
  et: ["Addis-Abeba", "Addis Ababa"],
  fj: ["Suva"],
  fi: ["Helsinki"],
  fr: ["Paris"],
  ga: ["Libreville"],
  gm: ["Banjul"],
  ge: ["Tbilissi", "Tbilisi"],
  gh: ["Accra"],
  gr: ["Athènes", "Athens", "Athina"],
  gd: ["Saint-Georges", "St. George's", "Saint George's"],
  gt: ["Guatemala", "Ciudad de Guatemala", "Guatemala City"],
  gn: ["Conakry"],
  gq: ["Malabo"],
  gw: ["Bissau"],
  gy: ["Georgetown"],
  ht: ["Port-au-Prince"],
  hn: ["Tegucigalpa"],
  hu: ["Budapest"],
  in: ["New Delhi", "Delhi", "Nouvelle-Delhi"],
  id: ["Jakarta", "Nusantara"],
  iq: ["Bagdad", "Baghdad"],
  ir: ["Téhéran", "Tehran"],
  ie: ["Dublin"],
  is: ["Reykjavik", "Reykjavík"],
  il: ["Jérusalem", "Jerusalem", "Tel Aviv", "Tel-Aviv"],
  it: ["Rome", "Roma"],
  jm: ["Kingston"],
  jp: ["Tokyo", "Tōkyō"],
  jo: ["Amman"],
  kz: ["Astana", "Nour-Soultan", "Nur-Sultan"],
  ke: ["Nairobi"],
  kg: ["Bichkek", "Bishkek"],
  ki: ["Tarawa", "Tarawa-Sud", "South Tarawa"],
  kw: ["Koweït", "Koweit", "Kuwait City", "Koweït City"],
  la: ["Vientiane"],
  ls: ["Maseru"],
  lv: ["Riga"],
  lb: ["Beyrouth", "Beirut"],
  lr: ["Monrovia"],
  ly: ["Tripoli"],
  li: ["Vaduz"],
  lt: ["Vilnius"],
  lu: ["Luxembourg"],
  mk: ["Skopje"],
  mg: ["Antananarivo", "Tananarive"],
  my: ["Kuala Lumpur", "Putrajaya"],
  mw: ["Lilongwe"],
  mv: ["Malé", "Male"],
  ml: ["Bamako"],
  mt: ["La Valette", "Valletta", "Valette"],
  ma: ["Rabat"],
  mh: ["Majuro", "Delap-Uliga-Darrit"],
  mu: ["Port-Louis", "Port Louis"],
  mr: ["Nouakchott"],
  mx: ["Mexico", "Ciudad de México", "Mexico City"],
  fm: ["Palikir"],
  md: ["Chișinău", "Chisinau", "Kichinev"],
  mc: ["Monaco"],
  mn: ["Oulan-Bator", "Ulaanbaatar", "Ulan Bator"],
  me: ["Podgorica"],
  mz: ["Maputo"],
  mm: ["Naypyidaw", "Nay Pyi Taw", "Rangoun", "Yangon"],
  na: ["Windhoek"],
  nr: ["Yaren"],
  np: ["Katmandou", "Kathmandu"],
  ni: ["Managua"],
  ne: ["Niamey"],
  ng: ["Abuja"],
  no: ["Oslo"],
  nz: ["Wellington"],
  om: ["Mascate", "Muscat"],
  ug: ["Kampala"],
  uz: ["Tachkent", "Tashkent"],
  pk: ["Islamabad"],
  pw: ["Ngerulmud", "Melekeok"],
  ps: ["Ramallah", "Jérusalem-Est", "Jérusalem", "Jerusalem"],
  pa: ["Panama", "Ciudad de Panamá", "Panama City"],
  pg: ["Port Moresby"],
  py: ["Asuncion", "Asunción"],
  nl: ["Amsterdam", "La Haye", "The Hague", "Den Haag"],
  pe: ["Lima"],
  ph: ["Manille", "Manila"],
  pl: ["Varsovie", "Warsaw", "Warszawa"],
  pt: ["Lisbonne", "Lisbon", "Lisboa"],
  qa: ["Doha"],
  ro: ["Bucarest", "Bucharest", "București"],
  gb: ["Londres", "London"],
  ru: ["Moscou", "Moscow", "Moskva"],
  rw: ["Kigali"],
  kn: ["Basseterre"],
  sm: ["Saint-Marin", "San Marino"],
  va: ["Vatican", "Cité du Vatican", "Vatican City"],
  vc: ["Kingstown"],
  lc: ["Castries"],
  sb: ["Honiara"],
  sv: ["San Salvador"],
  ws: ["Apia"],
  st: ["São Tomé", "Sao Tome"],
  sn: ["Dakar"],
  rs: ["Belgrade", "Beograd"],
  sc: ["Victoria"],
  sl: ["Freetown"],
  sg: ["Singapour", "Singapore"],
  sk: ["Bratislava"],
  si: ["Ljubljana"],
  so: ["Mogadiscio", "Mogadishu"],
  sd: ["Khartoum"],
  ss: ["Djouba", "Juba"],
  lk: ["Sri Jayawardenapura Kotte", "Kotte", "Colombo"],
  se: ["Stockholm"],
  ch: ["Berne", "Bern"],
  sr: ["Paramaribo"],
  sy: ["Damas", "Damascus"],
  tj: ["Douchanbé", "Dushanbe"],
  tz: ["Dodoma", "Dar es Salaam"],
  td: ["N'Djamena", "Ndjamena"],
  cz: ["Prague", "Praha"],
  th: ["Bangkok"],
  tl: ["Dili"],
  tg: ["Lomé", "Lome"],
  to: ["Nuku'alofa", "Nukualofa"],
  tt: ["Port-d'Espagne", "Port of Spain"],
  tn: ["Tunis"],
  tm: ["Achgabat", "Ashgabat"],
  tr: ["Ankara"],
  tv: ["Funafuti"],
  ua: ["Kiev", "Kyiv"],
  uy: ["Montevideo"],
  vu: ["Port-Vila", "Port Vila"],
  ve: ["Caracas"],
  vn: ["Hanoï", "Hanoi"],
  ye: ["Sanaa", "Sana'a"],
  zm: ["Lusaka"],
  zw: ["Harare"]
};
