/* Liste des pays souverains : code ISO 3166-1 alpha-2, nom français, synonymes acceptés.
   Le code sert à construire l'URL du drapeau : https://flagcdn.com/w640/<code>.png */
const COUNTRIES = [
  { code: "af", name: "Afghanistan", alt: [] },
  { code: "za", name: "Afrique du Sud", alt: ["south africa"] },
  { code: "al", name: "Albanie", alt: ["albania"] },
  { code: "dz", name: "Algérie", alt: ["algeria"] },
  { code: "de", name: "Allemagne", alt: ["germany", "deutschland"] },
  { code: "ad", name: "Andorre", alt: ["andorra"] },
  { code: "ao", name: "Angola", alt: [] },
  { code: "ag", name: "Antigua-et-Barbuda", alt: ["antigua and barbuda", "antigua"] },
  { code: "sa", name: "Arabie saoudite", alt: ["saudi arabia"] },
  { code: "ar", name: "Argentine", alt: ["argentina"] },
  { code: "am", name: "Arménie", alt: ["armenia"] },
  { code: "au", name: "Australie", alt: ["australia"] },
  { code: "at", name: "Autriche", alt: ["austria"] },
  { code: "az", name: "Azerbaïdjan", alt: ["azerbaijan"] },
  { code: "bs", name: "Bahamas", alt: [] },
  { code: "bh", name: "Bahreïn", alt: ["bahrain"] },
  { code: "bd", name: "Bangladesh", alt: [] },
  { code: "bb", name: "Barbade", alt: ["barbados"] },
  { code: "be", name: "Belgique", alt: ["belgium"] },
  { code: "bz", name: "Belize", alt: [] },
  { code: "bj", name: "Bénin", alt: ["benin"] },
  { code: "bt", name: "Bhoutan", alt: ["bhutan"] },
  { code: "by", name: "Biélorussie", alt: ["belarus", "bélarus"] },
  { code: "bo", name: "Bolivie", alt: ["bolivia"] },
  { code: "ba", name: "Bosnie-Herzégovine", alt: ["bosnie", "bosnia", "bosnia and herzegovina"] },
  { code: "bw", name: "Botswana", alt: [] },
  { code: "br", name: "Brésil", alt: ["brazil", "brasil"] },
  { code: "bn", name: "Brunei", alt: ["brunei darussalam"] },
  { code: "bg", name: "Bulgarie", alt: ["bulgaria"] },
  { code: "bf", name: "Burkina Faso", alt: ["burkina"] },
  { code: "bi", name: "Burundi", alt: [] },
  { code: "kh", name: "Cambodge", alt: ["cambodia"] },
  { code: "cm", name: "Cameroun", alt: ["cameroon"] },
  { code: "ca", name: "Canada", alt: [] },
  { code: "cv", name: "Cap-Vert", alt: ["cape verde", "cabo verde"] },
  { code: "cf", name: "République centrafricaine", alt: ["centrafrique", "central african republic", "rca"] },
  { code: "cl", name: "Chili", alt: ["chile"] },
  { code: "cn", name: "Chine", alt: ["china"] },
  { code: "cy", name: "Chypre", alt: ["cyprus"] },
  { code: "co", name: "Colombie", alt: ["colombia"] },
  { code: "km", name: "Comores", alt: ["comoros"] },
  { code: "cg", name: "République du Congo", alt: ["congo", "congo brazzaville", "republic of the congo"] },
  { code: "cd", name: "République démocratique du Congo", alt: ["rdc", "congo kinshasa", "drc", "zaire", "zaïre"] },
  { code: "kp", name: "Corée du Nord", alt: ["north korea"] },
  { code: "kr", name: "Corée du Sud", alt: ["south korea"] },
  { code: "cr", name: "Costa Rica", alt: [] },
  { code: "ci", name: "Côte d’Ivoire", alt: ["cote d'ivoire", "ivory coast"] },
  { code: "hr", name: "Croatie", alt: ["croatia"] },
  { code: "cu", name: "Cuba", alt: [] },
  { code: "dk", name: "Danemark", alt: ["denmark"] },
  { code: "dj", name: "Djibouti", alt: [] },
  { code: "dm", name: "Dominique", alt: ["dominica"] },
  { code: "do", name: "République dominicaine", alt: ["dominican republic", "saint domingue"] },
  { code: "eg", name: "Égypte", alt: ["egypt"] },
  { code: "ae", name: "Émirats arabes unis", alt: ["united arab emirates", "uae", "eau"] },
  { code: "ec", name: "Équateur", alt: ["ecuador"] },
  { code: "er", name: "Érythrée", alt: ["eritrea"] },
  { code: "es", name: "Espagne", alt: ["spain", "españa"] },
  { code: "ee", name: "Estonie", alt: ["estonia"] },
  { code: "sz", name: "Eswatini", alt: ["swaziland"] },
  { code: "us", name: "États-Unis", alt: ["usa", "united states", "etats unis d'amerique", "amerique"] },
  { code: "et", name: "Éthiopie", alt: ["ethiopia"] },
  { code: "fj", name: "Fidji", alt: ["fiji"] },
  { code: "fi", name: "Finlande", alt: ["finland", "suomi"] },
  { code: "fr", name: "France", alt: [] },
  { code: "ga", name: "Gabon", alt: [] },
  { code: "gm", name: "Gambie", alt: ["gambia"] },
  { code: "ge", name: "Géorgie", alt: ["georgia"] },
  { code: "gh", name: "Ghana", alt: [] },
  { code: "gr", name: "Grèce", alt: ["greece"] },
  { code: "gd", name: "Grenade", alt: ["grenada"] },
  { code: "gt", name: "Guatemala", alt: [] },
  { code: "gn", name: "Guinée", alt: ["guinea"] },
  { code: "gq", name: "Guinée équatoriale", alt: ["equatorial guinea"] },
  { code: "gw", name: "Guinée-Bissau", alt: ["guinea bissau"] },
  { code: "gy", name: "Guyana", alt: [] },
  { code: "ht", name: "Haïti", alt: ["haiti"] },
  { code: "hn", name: "Honduras", alt: [] },
  { code: "hu", name: "Hongrie", alt: ["hungary"] },
  { code: "in", name: "Inde", alt: ["india"] },
  { code: "id", name: "Indonésie", alt: ["indonesia"] },
  { code: "iq", name: "Irak", alt: ["iraq"] },
  { code: "ir", name: "Iran", alt: [] },
  { code: "ie", name: "Irlande", alt: ["ireland", "eire"] },
  { code: "is", name: "Islande", alt: ["iceland"] },
  { code: "il", name: "Israël", alt: ["israel"] },
  { code: "it", name: "Italie", alt: ["italy", "italia"] },
  { code: "jm", name: "Jamaïque", alt: ["jamaica"] },
  { code: "jp", name: "Japon", alt: ["japan"] },
  { code: "jo", name: "Jordanie", alt: ["jordan"] },
  { code: "kz", name: "Kazakhstan", alt: [] },
  { code: "ke", name: "Kenya", alt: [] },
  { code: "kg", name: "Kirghizistan", alt: ["kyrgyzstan", "kirghizie"] },
  { code: "ki", name: "Kiribati", alt: [] },
  { code: "kw", name: "Koweït", alt: ["kuwait"] },
  { code: "la", name: "Laos", alt: [] },
  { code: "ls", name: "Lesotho", alt: [] },
  { code: "lv", name: "Lettonie", alt: ["latvia"] },
  { code: "lb", name: "Liban", alt: ["lebanon"] },
  { code: "lr", name: "Liberia", alt: ["libéria"] },
  { code: "ly", name: "Libye", alt: ["libya"] },
  { code: "li", name: "Liechtenstein", alt: [] },
  { code: "lt", name: "Lituanie", alt: ["lithuania"] },
  { code: "lu", name: "Luxembourg", alt: [] },
  { code: "mk", name: "Macédoine du Nord", alt: ["macedoine", "north macedonia"] },
  { code: "mg", name: "Madagascar", alt: [] },
  { code: "my", name: "Malaisie", alt: ["malaysia"] },
  { code: "mw", name: "Malawi", alt: [] },
  { code: "mv", name: "Maldives", alt: [] },
  { code: "ml", name: "Mali", alt: [] },
  { code: "mt", name: "Malte", alt: ["malta"] },
  { code: "ma", name: "Maroc", alt: ["morocco"] },
  { code: "mh", name: "Îles Marshall", alt: ["marshall", "marshall islands"] },
  { code: "mu", name: "Maurice", alt: ["mauritius", "ile maurice"] },
  { code: "mr", name: "Mauritanie", alt: ["mauritania"] },
  { code: "mx", name: "Mexique", alt: ["mexico"] },
  { code: "fm", name: "Micronésie", alt: ["micronesia"] },
  { code: "md", name: "Moldavie", alt: ["moldova"] },
  { code: "mc", name: "Monaco", alt: [] },
  { code: "mn", name: "Mongolie", alt: ["mongolia"] },
  { code: "me", name: "Monténégro", alt: ["montenegro"] },
  { code: "mz", name: "Mozambique", alt: [] },
  { code: "mm", name: "Birmanie", alt: ["myanmar", "burma"] },
  { code: "na", name: "Namibie", alt: ["namibia"] },
  { code: "nr", name: "Nauru", alt: [] },
  { code: "np", name: "Népal", alt: ["nepal"] },
  { code: "ni", name: "Nicaragua", alt: [] },
  { code: "ne", name: "Niger", alt: [] },
  { code: "ng", name: "Nigeria", alt: ["nigéria"] },
  { code: "no", name: "Norvège", alt: ["norway"] },
  { code: "nz", name: "Nouvelle-Zélande", alt: ["new zealand"] },
  { code: "om", name: "Oman", alt: [] },
  { code: "ug", name: "Ouganda", alt: ["uganda"] },
  { code: "uz", name: "Ouzbékistan", alt: ["uzbekistan"] },
  { code: "pk", name: "Pakistan", alt: [] },
  { code: "pw", name: "Palaos", alt: ["palau"] },
  { code: "ps", name: "Palestine", alt: [] },
  { code: "pa", name: "Panama", alt: [] },
  { code: "pg", name: "Papouasie-Nouvelle-Guinée", alt: ["papouasie", "papua new guinea"] },
  { code: "py", name: "Paraguay", alt: [] },
  { code: "nl", name: "Pays-Bas", alt: ["netherlands", "hollande", "holland"] },
  { code: "pe", name: "Pérou", alt: ["peru"] },
  { code: "ph", name: "Philippines", alt: [] },
  { code: "pl", name: "Pologne", alt: ["poland"] },
  { code: "pt", name: "Portugal", alt: [] },
  { code: "qa", name: "Qatar", alt: [] },
  { code: "ro", name: "Roumanie", alt: ["romania"] },
  { code: "gb", name: "Royaume-Uni", alt: ["united kingdom", "uk", "angleterre", "grande bretagne", "great britain"] },
  { code: "ru", name: "Russie", alt: ["russia"] },
  { code: "rw", name: "Rwanda", alt: [] },
  { code: "kn", name: "Saint-Christophe-et-Niévès", alt: ["saint kitts et nevis", "saint kitts and nevis", "saint kitts"] },
  { code: "sm", name: "Saint-Marin", alt: ["san marino"] },
  { code: "va", name: "Vatican", alt: ["saint siege", "vatican city", "holy see"] },
  { code: "vc", name: "Saint-Vincent-et-les-Grenadines", alt: ["saint vincent", "saint vincent and the grenadines"] },
  { code: "lc", name: "Sainte-Lucie", alt: ["saint lucia"] },
  { code: "sb", name: "Îles Salomon", alt: ["salomon", "solomon islands"] },
  { code: "sv", name: "Salvador", alt: ["el salvador"] },
  { code: "ws", name: "Samoa", alt: [] },
  { code: "st", name: "Sao Tomé-et-Principe", alt: ["sao tome", "sao tome and principe"] },
  { code: "sn", name: "Sénégal", alt: ["senegal"] },
  { code: "rs", name: "Serbie", alt: ["serbia"] },
  { code: "sc", name: "Seychelles", alt: [] },
  { code: "sl", name: "Sierra Leone", alt: [] },
  { code: "sg", name: "Singapour", alt: ["singapore"] },
  { code: "sk", name: "Slovaquie", alt: ["slovakia"] },
  { code: "si", name: "Slovénie", alt: ["slovenia"] },
  { code: "so", name: "Somalie", alt: ["somalia"] },
  { code: "sd", name: "Soudan", alt: ["sudan"] },
  { code: "ss", name: "Soudan du Sud", alt: ["south sudan"] },
  { code: "lk", name: "Sri Lanka", alt: ["ceylan"] },
  { code: "se", name: "Suède", alt: ["sweden"] },
  { code: "ch", name: "Suisse", alt: ["switzerland", "schweiz", "helvetie"] },
  { code: "sr", name: "Suriname", alt: [] },
  { code: "sy", name: "Syrie", alt: ["syria"] },
  { code: "tj", name: "Tadjikistan", alt: ["tajikistan"] },
  { code: "tz", name: "Tanzanie", alt: ["tanzania"] },
  { code: "td", name: "Tchad", alt: ["chad"] },
  { code: "cz", name: "Tchéquie", alt: ["republique tcheque", "czech republic", "czechia"] },
  { code: "th", name: "Thaïlande", alt: ["thailand"] },
  { code: "tl", name: "Timor oriental", alt: ["timor leste", "east timor"] },
  { code: "tg", name: "Togo", alt: [] },
  { code: "to", name: "Tonga", alt: [] },
  { code: "tt", name: "Trinité-et-Tobago", alt: ["trinidad et tobago", "trinidad and tobago"] },
  { code: "tn", name: "Tunisie", alt: ["tunisia"] },
  { code: "tm", name: "Turkménistan", alt: ["turkmenistan"] },
  { code: "tr", name: "Turquie", alt: ["turkey", "türkiye"] },
  { code: "tv", name: "Tuvalu", alt: [] },
  { code: "ua", name: "Ukraine", alt: [] },
  { code: "uy", name: "Uruguay", alt: [] },
  { code: "vu", name: "Vanuatu", alt: [] },
  { code: "ve", name: "Venezuela", alt: [] },
  { code: "vn", name: "Viêt Nam", alt: ["vietnam"] },
  { code: "ye", name: "Yémen", alt: ["yemen"] },
  { code: "zm", name: "Zambie", alt: ["zambia"] },
  { code: "zw", name: "Zimbabwe", alt: [] }
];
